"""
Generate a complete text report from profiling results.
"""

import os
from datetime import datetime


def generate_text_report(
    report,
    thermal_report=None,
    gpu_summary=None,
    model_name="unknown",
    platform="Jetson",
    output_path="powerlens_report.txt",
):
    """Generate a complete text report file.

    Args:
        report: EnergyReport from profiling.
        thermal_report: Optional ThermalReport.
        gpu_summary: Optional dict from GpuMonitor.get_summary().
        model_name: Name of the model profiled.
        platform: Platform description.
        output_path: Where to save the report.

    Returns:
        Path to the saved report.
    """
    lines = []
    lines.append("=" * 60)
    lines.append("PowerLens Energy Profiling Report")
    lines.append("=" * 60)
    lines.append("")
    lines.append(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"Platform:  {platform}")
    lines.append(f"Model:     {model_name}")
    lines.append("")

    # Energy report
    lines.append(report.summary())

    # Thermal
    if thermal_report:
        lines.append(thermal_report.summary())

    # GPU
    if gpu_summary:
        lines.append("")
        lines.append("GPU Utilization")
        lines.append("=" * 42)
        lines.append(f"  GPU util:  avg={gpu_summary.get('gpu_util_avg_pct', 0):.0f}%  "
                     f"max={gpu_summary.get('gpu_util_max_pct', 0):.0f}%  "
                     f"min={gpu_summary.get('gpu_util_min_pct', 0):.0f}%")
        if "gpu_freq_avg_mhz" in gpu_summary:
            lines.append(f"  GPU freq:  avg={gpu_summary['gpu_freq_avg_mhz']:.0f}MHz  "
                        f"max={gpu_summary.get('gpu_freq_max_mhz', 0):.0f}MHz")
        lines.append("")

    # Per-inference details
    if report.inferences:
        lines.append("Per-Inference Details (first 10)")
        lines.append("-" * 60)
        lines.append(f"{'#':>4s} {'Energy (J)':>12s} {'Duration (ms)':>14s} {'Avg Power (W)':>14s}")
        for inf in report.inferences[:10]:
            lines.append(
                f"{inf.index:>4d} {inf.energy_j:>12.4f} "
                f"{inf.duration_s * 1000:>13.1f} {inf.avg_power_w:>13.2f}"
            )
        lines.append("")

    # Rail breakdown per inference
    if report.inferences and report.inferences[0].rail_energy_j:
        lines.append("Per-Rail Energy (first inference)")
        lines.append("-" * 42)
        for rail, energy in sorted(report.inferences[0].rail_energy_j.items()):
            lines.append(f"  {rail:20s} {energy:.4f} J")
        lines.append("")

    lines.append("=" * 60)
    lines.append("Report generated by PowerLens")
    lines.append("https://github.com/ssaserkar/powerlens")
    lines.append("=" * 60)

    text = "\n".join(lines)

    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w") as f:
        f.write(text)

    return output_path
